In [141]:
import pandas as pd
import numpy as np
from sklearn.cluster import MeanShift
from sklearn.metrics import pairwise_distances
from haversine import haversine, Unit

In [140]:
pip install haversine

Note: you may need to restart the kernel to use updated packages.


In [4]:
data = pd.read_csv('checkins.dat', sep='\|')

<ipython-input-4-cca919e5e99f>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  data = pd.read_csv('checkins.dat', sep='\|')


In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021967 entries, 0 to 1021966
Data columns (total 6 columns):
 #   Column               Non-Null Count    Dtype  
---  ------               --------------    -----  
 0   id                   1021967 non-null  object 
 1    user_id             1021966 non-null  float64
 2    venue_id            1021966 non-null  float64
 3        latitude        1021966 non-null  object 
 4        longitude       1021966 non-null  object 
 5        created_at      1021966 non-null  object 
dtypes: float64(2), object(4)
memory usage: 46.8+ MB


In [6]:
data.set_axis(['id', 'user_id', 'venue_id', 'latitude', 'longitude', 'created_at'], axis=1, inplace=True)

In [7]:
data['latitude'].replace('                   ', np.nan, inplace=True)
data['longitude'].replace('                   ', np.nan, inplace=True)

In [8]:
data.dropna(inplace=True)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 396634 entries, 1 to 1021964
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   id          396634 non-null  object 
 1   user_id     396634 non-null  float64
 2   venue_id    396634 non-null  float64
 3   latitude    396634 non-null  object 
 4   longitude   396634 non-null  object 
 5   created_at  396634 non-null  object 
dtypes: float64(2), object(4)
memory usage: 21.2+ MB


In [10]:
ms = MeanShift(bandwidth=0.1)

In [11]:
hundred_rows = data[:100000]
hundred_rows.shape

(100000, 6)

In [12]:
X = hundred_rows.loc[:,['latitude', 'longitude']]
X.shape

(100000, 2)

In [13]:
ms.fit(X)

MeanShift(bandwidth=0.1)

In [14]:
ms.cluster_centers_

array([[  40.7177164 ,  -73.99183542],
       [  33.44943805, -112.00213969],
       [  33.44638027, -111.90188756],
       ...,
       [ -37.8229826 ,  145.1811902 ],
       [ -41.2924945 ,  174.7732353 ],
       [ -45.0311622 ,  168.6626435 ]])

In [15]:
len(np.unique(ms.labels_))

3231

In [16]:
len(ms.labels_)

100000

In [17]:
val, counts = np.unique(ms.labels_, return_counts=True)

In [18]:
val, counts

(array([   0,    1,    2, ..., 3228, 3229, 3230], dtype=int64),
 array([12506,  4692,  3994, ...,     1,     1,     1], dtype=int64))

In [56]:
labels_15 = [x for x in val if counts[x]>15] 
labels_15

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [83]:
new_centers_list  = {i:tuple(ms.cluster_centers_[i+1]) for i in labels_15}
new_centers_list 

{0: (33.44943805020126, -112.00213969017547),
 1: (33.44638027037988, -111.90188756212359),
 2: (41.87824377967115, -87.62984336226329),
 3: (37.68868157406161, -122.40933037359147),
 4: (38.8861652155993, -77.04878333074303),
 5: (33.357344562325096, -111.82265410760392),
 6: (33.76663623218336, -84.39328918481657),
 7: (42.363218639848895, -71.07368760857386),
 8: (47.60624471741767, -122.33204382627093),
 9: (36.117229142990276, -115.17107342280688),
 10: (34.06039755458241, -118.24870902659876),
 11: (44.97794782033687, -93.2673008852605),
 12: (30.26718361698159, -97.74311928133027),
 13: (40.76687624004169, -73.83335349045205),
 14: (39.735830152625304, -104.98658042770822),
 15: (39.95168037300773, -75.16273592391683),
 16: (34.03548695312116, -118.43899771946148),
 17: (32.98089338217789, -117.07811797821928),
 18: (32.80302053531547, -96.76989743494408),
 19: (37.34787114392445, -121.94728722354373),
 20: (28.543501546632914, -81.37642862287088),
 21: (32.71134443394278, -117.

In [84]:
new_centers_list[0]

(33.44943805020126, -112.00213969017547)

In [81]:
offices = {1:(33.751277, -118.188740), 2:(25.867736, -80.324116), 3:(51.503016, -0.075479), 4:(52.378894, 4.885084), 5:(39.366487, 117.036146), 6:(-33.868457, 151.205134)}
offices

{1: (33.751277, -118.18874),
 2: (25.867736, -80.324116),
 3: (51.503016, -0.075479),
 4: (52.378894, 4.885084),
 5: (39.366487, 117.036146),
 6: (-33.868457, 151.205134)}

In [82]:
offices[1]

(33.751277, -118.18874)

In [24]:
for office in offices:
  for center in new_centers_list:
    dist = []
    dist.append((office, center, pairwise_distances(office.reshape(1, -1), center.reshape(1, -1))[0].item()))
  dist.sort(key=lambda x: x[2] )
  print(dist)

[(array([  33.751277, -118.18874 ]), array([ 38.4966573, -92.3437262]), 26.277050300857894)]
[(array([ 25.867736, -80.324116]), array([ 38.4966573, -92.3437262]), 17.43446823282945)]
[(array([51.503016, -0.075479]), array([ 38.4966573, -92.3437262]), 93.18044219681174)]
[(array([52.378894,  4.885084]), array([ 38.4966573, -92.3437262]), 98.21485645615154)]
[(array([ 39.366487, 117.036146]), array([ 38.4966573, -92.3437262]), 209.38167896498334)]
[(array([-33.868457, 151.205134]), array([ 38.4966573, -92.3437262]), 254.0723461385973)]


In [36]:
rows = new_centers_list.shape[0] +1
rows

593

In [37]:
cols = offices.shape[0] +1 
cols

7

In [49]:
matrix = np.zeros([rows,cols])

In [50]:
matrix.shape

(593, 7)

In [85]:
i = 1
for office in offices:
    print(matrix[0,i],office)
    matrix[0,i] = office
    i += 1
    

0.0 1
0.0 2
0.0 3
0.0 4
0.0 5
0.0 6


In [88]:
i = 1
for center in new_centers_list:
    print(matrix[i,0],center)
    matrix[i,0] = center
    i += 1
    

0.0 0
0.0 1
0.0 2
0.0 3
0.0 4
0.0 5
0.0 6
0.0 7
0.0 8
0.0 9
0.0 10
0.0 11
0.0 12
0.0 13
0.0 14
0.0 15
0.0 16
0.0 17
0.0 18
0.0 19
0.0 20
0.0 21
0.0 22
0.0 23
0.0 24
0.0 25
0.0 26
0.0 27
0.0 28
0.0 29
0.0 30
0.0 31
0.0 32
0.0 33
0.0 34
0.0 35
0.0 36
0.0 37
0.0 38
0.0 39
0.0 40
0.0 41
0.0 42
0.0 43
0.0 44
0.0 45
0.0 46
0.0 47
0.0 48
0.0 49
0.0 50
0.0 51
0.0 52
0.0 53
0.0 54
0.0 55
0.0 56
0.0 57
0.0 58
0.0 59
0.0 60
0.0 61
0.0 62
0.0 63
0.0 64
0.0 65
0.0 66
0.0 67
0.0 68
0.0 69
0.0 70
0.0 71
0.0 72
0.0 73
0.0 74
0.0 75
0.0 76
0.0 77
0.0 78
0.0 79
0.0 80
0.0 81
0.0 82
0.0 83
0.0 84
0.0 85
0.0 86
0.0 87
0.0 88
0.0 89
0.0 90
0.0 91
0.0 92
0.0 93
0.0 94
0.0 95
0.0 96
0.0 97
0.0 98
0.0 99
0.0 100
0.0 101
0.0 102
0.0 103
0.0 104
0.0 105
0.0 106
0.0 107
0.0 108
0.0 109
0.0 110
0.0 111
0.0 112
0.0 113
0.0 114
0.0 115
0.0 116
0.0 117
0.0 118
0.0 119
0.0 120
0.0 121
0.0 122
0.0 123
0.0 124
0.0 125
0.0 126
0.0 127
0.0 128
0.0 129
0.0 130
0.0 131
0.0 132
0.0 133
0.0 134
0.0 135
0.0 136
0.0 137
0.0 13

In [89]:
matrix

array([[0.000e+00, 1.000e+00, 2.000e+00, ..., 4.000e+00, 5.000e+00,
        6.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [8.840e+02, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.343e+03, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.350e+03, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

In [103]:
range(1,matrix.shape[1])

range(1, 7)

In [104]:
range(1,matrix.shape[0])

range(1, 593)

In [113]:
new_centers_list.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

In [114]:
offices.keys()

dict_keys([1, 2, 3, 4, 5, 6])

In [160]:
df = pd.DataFrame(index=new_centers_list.keys(), columns=offices.keys())
df

1    2    3    4    5    6
0     NaN  NaN  NaN  NaN  NaN  NaN
1     NaN  NaN  NaN  NaN  NaN  NaN
2     NaN  NaN  NaN  NaN  NaN  NaN
3     NaN  NaN  NaN  NaN  NaN  NaN
4     NaN  NaN  NaN  NaN  NaN  NaN
...   ...  ...  ...  ...  ...  ...
684   NaN  NaN  NaN  NaN  NaN  NaN
727   NaN  NaN  NaN  NaN  NaN  NaN
884   NaN  NaN  NaN  NaN  NaN  NaN
1343  NaN  NaN  NaN  NaN  NaN  NaN
1350  NaN  NaN  NaN  NaN  NaN  NaN

[592 rows x 6 columns]

In [161]:
for office in offices:
    for center in new_centers_list:
        #print(offices[office], (new_centers_list[center]), haversine(offices[office], new_centers_list[center]))
        df.loc[center,office] = haversine(offices[office], new_centers_list[center])
        print(offices[office], new_centers_list[center], df.loc[center,office])

(33.751277, -118.18874) (33.44943805020126, -112.00213969017547) 573.8758570672139
(33.751277, -118.18874) (33.44638027037988, -111.90188756212359) 583.1709165566696
(33.751277, -118.18874) (41.87824377967115, -87.62984336226329) 2814.88052997668
(33.751277, -118.18874) (37.68868157406161, -122.40933037359147) 580.2553856970569
(33.751277, -118.18874) (38.8861652155993, -77.04878333074303) 3698.28759614233
(33.751277, -118.18874) (33.357344562325096, -111.82265410760392) 591.4471609158442
(33.751277, -118.18874) (33.76663623218336, -84.39328918481657) 3109.934414225575
(33.751277, -118.18874) (42.363218639848895, -71.07368760857386) 4179.191451614648
(33.751277, -118.18874) (47.60624471741767, -122.33204382627093) 1579.1122868449002
(33.751277, -118.18874) (36.117229142990276, -115.17107342280688) 380.5953502947844
(33.751277, -118.18874) (34.06039755458241, -118.24870902659876) 34.81537624382416
(33.751277, -118.18874) (44.97794782033687, -93.2673008852605) 2464.6700241659173
(33.7512

In [162]:
df

1        2        3        4        5        6
0     573.876  3161.24  8480.19  8684.05  10474.7  12553.9
1     583.171  3151.97  8474.93  8679.15  10480.4  12562.1
2     2814.88  1901.89  6356.41  6606.78  10643.8  14876.2
3     580.255  4150.57  8626.88   8779.6  9517.97    11944
4     3698.29   1479.6  5903.52  6190.59  11196.3  15709.4
...       ...      ...      ...      ...      ...      ...
684   2757.91  1880.84  6424.73     6675  10670.3  14817.9
727   2122.36  2225.41  6910.09  7140.19  10459.5  14184.4
884   2113.74   2231.7  6916.38  7146.18  10455.8  14175.8
1343  3600.13  1494.54  5954.74  6238.23  11144.5  15618.8
1350   2372.1  1799.68  6905.51  7155.08  10853.7  14402.1

[592 rows x 6 columns]

In [165]:
df['min_to_center']=df.min(axis=1)

In [166]:
df

1        2        3        4        5        6  min_to_center
0     573.876  3161.24  8480.19  8684.05  10474.7  12553.9     573.875857
1     583.171  3151.97  8474.93  8679.15  10480.4  12562.1     583.170917
2     2814.88  1901.89  6356.41  6606.78  10643.8  14876.2    1901.886859
3     580.255  4150.57  8626.88   8779.6  9517.97    11944     580.255386
4     3698.29   1479.6  5903.52  6190.59  11196.3  15709.4    1479.595521
...       ...      ...      ...      ...      ...      ...            ...
684   2757.91  1880.84  6424.73     6675  10670.3  14817.9    1880.843267
727   2122.36  2225.41  6910.09  7140.19  10459.5  14184.4    2122.356183
884   2113.74   2231.7  6916.38  7146.18  10455.8  14175.8    2113.743771
1343  3600.13  1494.54  5954.74  6238.23  11144.5  15618.8    1494.541380
1350   2372.1  1799.68  6905.51  7155.08  10853.7  14402.1    1799.677642

[592 rows x 7 columns]

In [169]:
df = df.sort_values('min_to_center')

In [170]:
df

1        2        3         4        5         6  min_to_center
369  8964.72  7445.73  353.949  0.822119  7902.46   16643.1       0.822119
419  12061.7  15018.8  16990.1   16642.6  8868.96  0.870904       0.870904
418  3736.26  2.50848  7132.39    7446.6  12543.3   15018.4       2.508478
57   8780.95  7127.54  3.46484    356.93  8221.22   16993.8       3.464836
50   7.48343  3731.54  8776.08   8956.42  10095.5   12068.5       7.483432
..       ...      ...      ...       ...      ...       ...            ...
102  15455.9  12689.6  6703.87   6556.76  9214.95   12243.5    6556.758560
104  9885.01  6582.75   9499.6   9805.46  17679.7   13357.3    6582.745917
432  8972.75  6673.28  11667.9   12004.7  19067.2   11354.3    6673.277127
261  10120.5  6736.52  9280.63   9578.39  17402.6   13520.6    6736.516169
447  9826.21  7111.76  11130.3   11445.8  19347.6   11800.8    7111.756829

[592 rows x 7 columns]

In [176]:
df[:20]

1        2        3         4        5         6  min_to_center
369  8964.72  7445.73  353.949  0.822119  7902.46   16643.1       0.822119
419  12061.7  15018.8  16990.1   16642.6  8868.96  0.870904       0.870904
418  3736.26  2.50848  7132.39    7446.6  12543.3   15018.4       2.508478
57   8780.95  7127.54  3.46484    356.93  8221.22   16993.8       3.464836
50   7.48343  3731.54  8776.08   8956.42  10095.5   12068.5       7.483432
28   3748.15  13.9971  7130.37   7444.92  12552.2   15025.1      13.997140
166  3745.59  18.5104  7141.39   7455.97  12559.3   15015.5      18.510382
86   19.9762  3722.86  8763.68   8944.17  10094.6   12080.8      19.976194
91   3740.21  20.1156  7110.91   7425.02  12528.5   15036.4      20.115640
41   20.9679  3751.61  8781.26   8960.62  10077.6   12054.7      20.967921
290   24.679  3734.45  8762.09   8941.89  10080.4   12075.7      24.679001
26   28.4571  3707.83  8762.05   8943.35    10110   12089.7      28.457072
319  3722.34  30.1632  7109.61   7423.18  12511.3   15029.6      30.163186
118  30.8154  3719.72  8752.73    8933.1  10088.8   12089.3      30.815411
31   31.6964  3703.86  8773.53   8955.36  10124.2   12084.7      31.696429
54    3739.3  32.6323  7099.11   7413.08  12517.6     15045      32.632338
10   34.8154  3742.47  8758.14   8937.38  10068.2   12073.9      34.815376
158  3727.46  37.7307   7098.9   7412.51  12506.8     15040      37.730686
16   39.1445  3759.79  8770.23   8948.83  10059.1   12057.2      39.144476
49   41.9088  3693.85  8770.13   8952.44  10132.4   12092.1      41.908823

In [173]:
new_centers_list[369]

(52.37296399032261, 4.892317222580647)

In [174]:
offices[4]

(52.378894, 4.885084)

In [175]:
haversine(new_centers_list[369],offices[4] )

0.8221191867996301