In [53]:
import pandas as pd


In [54]:
data = pd.read_csv('titanic.csv', index_col = 'PassengerId')
data.replace(to_replace='female',value = 0, inplace=True)
data.replace(to_replace='male',value = 1, inplace=True)
data

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name  Sex   Age  \
PassengerId                                                                 
1                                      Braund, Mr. Owen Harris    1  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0   
3                                       Heikkinen, Miss. Laina    0  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0   
5                                     Allen, Mr. William Henry    1  35.0   
...                                                        ...  ...   ...   
887                                      Montvila, Rev. Juozas    1  27.0   
888                               Graham, Miss. Margaret Edith    0  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"    0   NaN   
890                                      Behr, Mr. Karl Howell    1  26.0   
891                                        Dooley, Mr. Patrick    1  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [55]:
data.shape
#data.dropna(inplace=True)


(891, 11)

In [73]:
X=data[['Pclass','Fare', 'Age', 'Sex', 'Survived' ]].dropna()
X.isnull()



Pclass   Fare    Age    Sex  Survived
PassengerId                                       
1             False  False  False  False     False
2             False  False  False  False     False
3             False  False  False  False     False
4             False  False  False  False     False
5             False  False  False  False     False
...             ...    ...    ...    ...       ...
886           False  False  False  False     False
887           False  False  False  False     False
888           False  False  False  False     False
890           False  False  False  False     False
891           False  False  False  False     False

[714 rows x 5 columns]

In [74]:
Y = X['Survived']
Y.isnull()

PassengerId
1      False
2      False
3      False
4      False
5      False
       ...  
886    False
887    False
888    False
890    False
891    False
Name: Survived, Length: 714, dtype: bool

In [75]:
X=X[['Pclass','Fare', 'Age', 'Sex' ]]
X

Pclass     Fare   Age  Sex
PassengerId                            
1                 3   7.2500  22.0    1
2                 1  71.2833  38.0    0
3                 3   7.9250  26.0    0
4                 1  53.1000  35.0    0
5                 3   8.0500  35.0    1
...             ...      ...   ...  ...
886               3  29.1250  39.0    0
887               2  13.0000  27.0    1
888               1  30.0000  19.0    0
890               1  30.0000  26.0    1
891               3   7.7500  32.0    1

[714 rows x 4 columns]

In [76]:
from sklearn import tree 
import numpy as np

In [77]:
decision_tree = tree.DecisionTreeClassifier(random_state=241)
clf = decision_tree.fit(X, Y)
clf.feature_importances_

array([0.14000522, 0.30343647, 0.2560461 , 0.30051221])

In [81]:
clf = decision_tree.fit(X, Y)
#clf.feature_importances_
#importances = pd.DataFrame({'feature':X,'importance':np.round(clf.feature_importances_,3)})
#importances = importances.sort_values('importance',ascending=False).set_index('feature')
print(X.columns, clf.feature_importances_)
#print (importances)
#importances.plot.bar()

Index(['Pclass', 'Fare', 'Age', 'Sex'], dtype='object') [0.14000522 0.30343647 0.2560461  0.30051221]


In [34]:
from sklearn.feature_selection import SelectKBest
test = SelectKBest(k=4)
fit = test.fit(X, Y)
print(fit.scores_)


[ 0.21622049  3.32159688 12.49163877 71.60592301]


In [35]:
features = fit.transform(X)

In [36]:
features

array([[  1.    ,  71.2833,  38.    ,   0.    ],
       [  1.    ,  53.1   ,  35.    ,   0.    ],
       [  1.    ,  51.8625,  54.    ,   1.    ],
       [  3.    ,  16.7   ,   4.    ,   0.    ],
       [  1.    ,  26.55  ,  58.    ,   0.    ],
       [  2.    ,  13.    ,  34.    ,   1.    ],
       [  1.    ,  35.5   ,  28.    ,   1.    ],
       [  1.    , 263.    ,  19.    ,   1.    ],
       [  1.    ,  76.7292,  49.    ,   0.    ],
       [  1.    ,  61.9792,  65.    ,   1.    ],
       [  1.    ,  83.475 ,  45.    ,   1.    ],
       [  2.    ,  10.5   ,  29.    ,   0.    ],
       [  3.    ,   7.65  ,  25.    ,   1.    ],
       [  1.    , 263.    ,  23.    ,   0.    ],
       [  1.    ,  61.175 ,  46.    ,   1.    ],
       [  1.    ,  34.6542,  71.    ,   1.    ],
       [  1.    ,  63.3583,  23.    ,   1.    ],
       [  1.    ,  77.2875,  21.    ,   1.    ],
       [  1.    ,  52.    ,  47.    ,   1.    ],
       [  1.    , 247.5208,  24.    ,   1.    ],
       [  2.    ,  1